import type { NextPage } from 'next'
import Head from 'next/head'
import React, { FC } from "react";
import dynamic from 'next/dynamic'
import Link from 'next/link';

const LoadingIndicator: FC<{}> = () => <h1>Lodaing componement...</h1>

const Archive = dynamic(
  () => import('../features/archive/archive'),
  {
    ssr: false,
    suspense: false,
    loading: LoadingIndicator 
  }
)

const History: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>Serverside gives this much</div>
        <Archive />
      </div>

      <footer className={`footer`}>
        <Link href="/">
          <a>Main</a>
        </Link>
      </footer>
    </>
  )
}

export default History