import type { NextPage } from 'next'
import Head from 'next/head'
import Archive from '../features/archive/archive'
import styled from 'styled-components'

const RestyledArchive = styled(Archive)`
  margin: 0; padding: 0;
  flex: 1 0 auto;

  font-family: 'Dekko';
  font-size: 1.2em;
`

const History: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        In History page you can browse the archive:
        <Archive />

      </div>
    </>
  )
}

export default History