import type { NextPage } from 'next'
import Head from 'next/head'
import PracticeProxy from '../features/practice/practiceProxy'
import styled from 'styled-components'

const RestyledPracticeProxy = styled(PracticeProxy)`
  margin: 0; padding: 0;
  flex: 1 0 auto;

  font-family: 'Dekko';
  font-size: 1.2em;
`

const Practice: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RestyledPracticeProxy />
    </>
  )
}

export default Practice