import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import PracticeComponent from '../practice/practice'

const Practice: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PracticeComponent />
      </main>

      <footer className={styles.footer}>
        <Link href="/">
          <a>Back</a>
        </Link>
      </footer>
    </div>
  )
}

export default Practice