import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Counter from '../features/counter/counter'
import Link from 'next/link'
import Kanye from '../features/ye/kanye'

const Zoo: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Counter />
      <Kanye />
      <footer className={styles.footer}>
        <Link href="/">
          <a>Home</a>
        </Link>
      </footer>
    </div>
  )
}

export default Zoo